sneak_to_select: true
sneak_to_deselect: true
default_distance: 10

entity_select: "&aEntity selected."
entity_deselect: "&cEntity deselected."
entity_deselect_death: "&cEntity unavailable, deselecting..."
entity_already_selected: "&cYou have already entity selected! Deselect first."

