sneak_to_select: true
sneak_to_deselect: true
default_distance: 10

entity_select: "&aEntity selected."
entity_deselect: "&cEntity deselected."
entity_deselect_death: "&cEntity unavailable, deselecting..."
entity_already_selected: "&cYou have already entity selected! Deselect first."
unknown_command: "&cSorry, but i don't recognize this command."
reload_start: "&7Reloading..."
reload_end: "&aReloaded!"

scroll_zoom: true
changed_distance: "&aDistance changed to %distance%"
distance_limit_min: 2
distance_limit_max: 20
distance_scroll_step: 0.2
death_particles: true
allow_players: false
allow_boat_minecart: false
allow_monsters: true
fall_damage: true