name: EntitySmasher
version: 1.1
main: EntitySmasher.EntitySmasher
api-version: 1.13
commands:
  es:
    description: Main command for EntitySmasher plugin.
    usage: /es
permissions:
  entitysmasher.use:
    description: Allow picking/placing entities
    default: true
  entitysmasher.zoom:
    description: Allow scroll to change distance
    default: true